<?php

namespace GJGNY\DataToolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LeadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadRepository extends EntityRepository
{
/*    public function findUniqueProgramSources()
    {
        $qb = $this->createQueryBuilder('l');
        $qb->groupBy('programSource');
        
        $programSources = $qb->getQuery()->getResult();
        
        echo count($programSources);
        
        return array('a','b');
    } */
}