<?php

namespace GJGNY\DataToolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PortalPartnerLogoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortalPartnerLogoRepository extends EntityRepository
{
}