<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * @var string $firstName
     */
    protected $firstName;
    /**
     * @var string $lastName
     */
    protected $lastName;
    /**
     * @var string $organization
     */
    protected $organization;
    /**
     * @var string $county
     */
    protected $county;

    protected $LeadEventsEntered;
    protected $LeadEventsUpdated;
    protected $LeadsEntered;
    protected $LeadsUpdated;
    protected $LeadsAssignedTo;
    protected $ProgramsUpdated;
    protected $ProgramsEntered;
    protected $notificationPortals;
    
    public function __toString()
    {
        return $this->firstName.' '.$this->lastName;
    }
    
    /**
     * Get firstName
     *
     * @return string $firstName
     */
    public function getFirstName()
    {
        return $this->firstName;
    }
    /**
     * Set firstName
     *
     * @return string $firstName
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;
    }
    /**
     * Get lastName
     *
     * @return string $lastName
     */
    public function getLastName()
    {
        return $this->lastName;
    }
    /**
     * Set lastName
     *
     * @return string $lastName
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;
    }
    /**
     * Get organization
     *
     * @return string $organization
     */
    public function getOrganization()
    {
        return $this->organization;
    }
    /**
     * Set organization
     *
     * @return string $organization
     */
    public function setOrganization($organization)
    {
        $this->organization = $organization;
    }
    /**
     * Get county
     *
     * @return string $county
     */
    public function getCounty()
    {
        return $this->county;
    }
    /**
     * Set county
     *
     * @return string $county
     */
    public function setCounty($county)
    {
        $this->county = $county;
    }
    
    /**
     * Add LeadEventsEntered
     *
     * @param GJGNY\DataToolBundle\Entity\LeadEvent $leadEventsEntered
     */
    public function addLeadEventsEntered(\GJGNY\DataToolBundle\Entity\LeadEvent $leadEventsEntered)
    {
        $this->LeadEventsEntered[] = $leadEventsEntered;
    }

    /**
     * Get LeadEventsEntered
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getLeadEventsEntered()
    {
        return $this->LeadEventsEntered;
    }

    /**
     * Add LeadEventsUpdated
     *
     * @param GJGNY\DataToolBundle\Entity\LeadEvent $leadEventsUpdated
     */
    public function addLeadEventsUpdated(\GJGNY\DataToolBundle\Entity\LeadEvent $leadEventsUpdated)
    {
        $this->LeadEventsUpdated[] = $leadEventsUpdated;
    }

    /**
     * Get LeadEventsUpdated
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getLeadEventsUpdated()
    {
        return $this->LeadEventsUpdated;
    }

    /**
     * Add LeadsEntered
     *
     * @param GJGNY\DataToolBundle\Entity\Lead $leadsEntered
     */
    public function addLeadsEntered(\GJGNY\DataToolBundle\Entity\Lead $leadsEntered)
    {
        $this->LeadsEntered[] = $leadsEntered;
    }

    /**
     * Get LeadsEntered
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getLeadsEntered()
    {
        return $this->LeadsEntered;
    }
    /**
     * Add LeadsAssignedTo
     *
     * @param GJGNY\DataToolBundle\Entity\Lead $LeadsAssignedTo
     */
    public function addLeadsAssignedTo(\GJGNY\DataToolBundle\Entity\Lead $LeadsAssignedTo)
    {
        $this->LeadsAssignedTo[] = $LeadsAssignedTo;
    }

    /**
     * Get LeadsAssignedTo
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getLeadsAssignedTo()
    {
        return $this->LeadsAssignedTo;
    }
    /**
     * Add LeadsUpdated
     *
     * @param GJGNY\DataToolBundle\Entity\Lead $leadsUpdated
     */
    public function addLeadsUpdated(\GJGNY\DataToolBundle\Entity\Lead $leadsUpdated)
    {
        $this->LeadsUpdated[] = $leadsUpdated;
    }

    /**
     * Get LeadsUpdated
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getLeadsUpdated()
    {
        return $this->LeadsUpdated;
    }

    /**
     * Add LeadEventsEntered
     *
     * @param GJGNY\DataToolBundle\Entity\LeadEvent $leadEventsEntered
     */
    public function addLeadEvent(\GJGNY\DataToolBundle\Entity\LeadEvent $leadEventsEntered)
    {
        $this->LeadEventsEntered[] = $leadEventsEntered;
    }

    /**
     * Add LeadsEntered
     *
     * @param GJGNY\DataToolBundle\Entity\Lead $leadsEntered
     */
    public function addLead(\GJGNY\DataToolBundle\Entity\Lead $leadsEntered)
    {
        $this->LeadsEntered[] = $leadsEntered;
    }

    /**
     * Add ProgramsUpdated
     *
     * @param GJGNY\DataToolBundle\Entity\Program $programsUpdated
     */
    public function addProgram(\GJGNY\DataToolBundle\Entity\Program $programsUpdated)
    {
        $this->ProgramsUpdated[] = $programsUpdated;
    }

    /**
     * Get ProgramsUpdated
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getProgramsUpdated()
    {
        return $this->ProgramsUpdated;
    }

    /**
     * Get ProgramsEntered
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getProgramsEntered()
    {
        return $this->ProgramsEntered;
    }
    
    /**
     * Add notificationPortals
     *
     * @param GJGNY\DataToolBundle\Entity\PortalSettings $notificationPortals
     */
    public function addPortalSettings(\GJGNY\DataToolBundle\Entity\PortalSettings $notificationPortals)
    {
        $this->notificationPortals[] = $notificationPortals;
    }

    /**
     * Get notificationPortals
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getNotificationPortals()
    {
        return $this->notificationPortals;
    }
  
}