imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['php','twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
    translator: { fallback: en }
        
services:
    gjgny.datatool.admin.lead:
      class: GJGNY\DataToolBundle\Admin\LeadAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Leads, label: Leads }
      arguments: [null, GJGNY\DataToolBundle\Entity\Lead, GJGNYDataToolBundle:LeadAdmin]
    gjgny.datatool.admin.leadevent:
      class: GJGNY\DataToolBundle\Admin\LeadEventAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Leads, label: Lead Events }
      arguments: [null, GJGNY\DataToolBundle\Entity\LeadEvent, GJGNYDataToolBundle:LeadEventAdmin]
    gjgny.datatool.admin.program:
      class: GJGNY\DataToolBundle\Admin\ProgramAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Programs, label: Programs }
      arguments: [null, GJGNY\DataToolBundle\Entity\Program, GJGNYDataToolBundle:ProgramAdmin]
       
    gjgny:
      class: GJGNY\DataToolBundle\Resources\classes\Config
      arguments: [{Broome: flint@igc.org, Tompkins : scl36@cornell.edu}, {Broome: [moniquereeser@gmail.com, flint@igc.org, murdanick@gmail.com], Tompkins: [scl36@cornell.edu, ml637@cornell.edu ] }]   
    
    errorReports:
      class: CCETC\ErrorReportBundle\Resources\config\Config
      arguments: [haggertypat@gmail.com]   

sonata_admin:
   title: GJGNY Data Tool
   expanded_menu: true

  
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      adminTitle: "GJGNY Data Tool"
      adminEmail: "haggertypat@gmail.com"
      expandedMenu: true

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                mappings:
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~
                    GJGNYDataToolBundle: ~
                    FOSUserBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:
       type: file
       path: %kernel.root_dir%/spool
  

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# FOS user bundle
fos_user:
  db_driver: orm
  firewall_name: main
  user_class: Application\Sonata\UserBundle\Entity\User
  from_email:
    address: noreply@ccetompkins.org
    sender_name:    GJGNY Data Tool
  registration:
    approval:
      enabled:    true
      template:   FOSUserBundle:Registration:email.txt.twig
  settings:
    application_title: GJGNY Data Tool
    admin_email: haggertypat@gmail.com
    base_layout: SonataAdminBundle::standard_layout.html.twig
    use_page_header: true
    flash_name: sonata_flash_success
    
parameters:
   security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap    