imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
       engines: ['php','twig']
       assets_version: 2.0.0
    session:
        default_locale: %locale%
        auto_start:     true
    translator: { fallback: en }
        
services:   
    gjgny:
      class: GJGNY\DataToolBundle\Resources\classes\Config
      arguments: [{Broome: flint@igc.org, Tompkins : scl36@cornell.edu}, {Broome: [moniquereeser@gmail.com, flint@igc.org, murdanick@gmail.com], Tompkins: [scl36@cornell.edu, ml637@cornell.edu ] }]   
    
    errorReports:
      class: CCETC\ErrorReportBundle\Resources\config\Config
      arguments: [haggertypat@gmail.com]  
    
    gjgny.datatool.admin.lead:
      class: GJGNY\DataToolBundle\Admin\LeadAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Leads, label: Leads }
      arguments: [null, GJGNY\DataToolBundle\Entity\Lead, GJGNYDataToolBundle:LeadAdmin]
    gjgny.datatool.admin.leadevent:
      class: GJGNY\DataToolBundle\Admin\LeadEventAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Leads, label: Lead Events }
      arguments: [null, GJGNY\DataToolBundle\Entity\LeadEvent, GJGNYDataToolBundle:LeadEventAdmin]
    gjgny.datatool.admin.program:
      class: GJGNY\DataToolBundle\Admin\ProgramAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Programs, label: Programs }
      arguments: [null, GJGNY\DataToolBundle\Entity\Program, GJGNYDataToolBundle:ProgramAdmin]

    gjgny.datatool.admin.portal:
      class: GJGNY\DataToolBundle\Admin\PortalAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Portals, label: Portals }
      arguments: [null, GJGNY\DataToolBundle\Entity\Portal, GJGNYDataToolBundle:PortalAdmin]
    gjgny.datatool.admin.portalpartnerlogo:
      class: GJGNY\DataToolBundle\Admin\PortalPartnerLogoAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Portals, label: Partner Logos }
      arguments: [null, GJGNY\DataToolBundle\Entity\PortalPartnerLogo, GJGNYDataToolBundle:PortalPartnerLogoAdmin]
    gjgny.datatool.admin.portalsettings:
      class: GJGNY\DataToolBundle\Admin\PortalSettingsAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Portals, label: Portal Settings }
      arguments: [null, GJGNY\DataToolBundle\Entity\PortalSettings, GJGNYDataToolBundle:PortalSettingsAdmin]
    gjgny.datatool.admin.contractor:
      class: GJGNY\DataToolBundle\Admin\ContractorAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Portals, label: Contractors }
      arguments: [null, GJGNY\DataToolBundle\Entity\Contractor, GJGNYDataToolBundle:ContractorAdmin] 
    gjgny.datatool.admin.county:
      class: GJGNY\DataToolBundle\Admin\CountyAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Settings, label: Counties }
      arguments: [null, GJGNY\DataToolBundle\Entity\County, GJGNYDataToolBundle:CountyAdmin] 
    gjgny.datatool.admin.testimonial:
      class: GJGNY\DataToolBundle\Admin\TestimonialAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Portals, label: Testimonials }
      arguments: [null, GJGNY\DataToolBundle\Entity\Testimonial, GJGNYDataToolBundle:TestimonialAdmin] 


parameters:
   security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap   
   
sonata_admin:
   security:
      handler: sonata.admin.security.handler.acl
      information:
          GUEST:    [VIEW, LIST]
          STAFF:    [EDIT, LIST, CREATE]
          EDITOR:   [OPERATOR]
          ADMIN:    [MASTER]
   title: GJGNY Data Tool
   expanded_menu: false
   
fos_user:
  db_driver: orm
  firewall_name: main
  user_class: Application\Sonata\UserBundle\Entity\User
  from_email:
    address: noreply@ccetompkins.org
    sender_name:    GJGNY Data Tool
  registration:
    approval:
      enabled:    true
      template:   FOSUserBundle:Registration:email.txt.twig
  settings:
    application_title: GJGNY Data Tool
    admin_email: haggertypat@gmail.com
    base_layout: SonataAdminBundle::standard_layout.html.twig
    use_page_header: true
    flash_name: sonata_flash_success
      
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      adminTitle: "GJGNY Data Tool"
      adminEmail: "haggertypat@gmail.com"
      expandedMenu: true

assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                mappings:
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~
                    GJGNYDataToolBundle: ~
                    FOSUserBundle: ~
                    CCETCErrorReportBundle: ~

swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:
       type: file
       path: %kernel.root_dir%/spool

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false 