homeDefault:
  pattern:  /
  defaults: { _controller: SonataAdminBundle:Core:dashboard }

portal:
  pattern: /portal/{url}
  defaults: { _controller: GJGNYDataToolBundle:Portal:portal }

home:
  pattern:  /admin/dashboard
  defaults: { _controller: SonataAdminBundle:Core:dashboard }
  
adminHelp:
  pattern: /help
  defaults: { _controller: CCETCErrorReportBundle:ErrorReport:errorReport, usePageHeader: true, flash: sonata_flash_success, redirect: adminHome, baseLayout: "SonataAdminBundle::standard_layout.html.twig", formRoute: adminHelp }
  
adminHome:
  pattern: /admin/dashboard
  defaults: { _controller: SonataAdminBundle:Core:dashboard }
  
getProgramDate:
  pattern: /getProgramDate/{id}
  defaults: { _controller: GJGNYDataToolBundle:Program:getProgramDate, id: 0 }
  
sonata_user_impersonating:
  pattern: /admin/dashboard
  defaults: { _controller: SonataAdminBundle:Core:dashboard }
  
# ADMIN =====================
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
        
    
# FOSUser Bundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password  
  